Traceback (most recent call last):
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jqbon\anaconda3\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\jqbon\anaconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
test = 7         #An integer
# test = 7.0       #A floating point decimal
# test = True      #A boolean
# test = 4.75 + 3j #A complex number

iterable = test
for var in iterable:
    print(var)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[25], line 7[0m
[0;32m      2[0m [38;5;66;03m# test = 7.0       #A floating point decimal[39;00m
[0;32m      3[0m [38;5;66;03m# test = True      #A boolean[39;00m
[0;32m      4[0m [38;5;66;03m# test = 4.75 + 3j #A complex number[39;00m
[0;32m      6[0m iterable [38;5;241m=[39m test
[1;32m----> 7[0m [38;5;28;01mfor[39;00m var [38;5;129;01min[39;00m iterable:
[0;32m      8[0m     [38;5;28mprint[39m(var)

[1;31mTypeError[0m: 'int' object is not iterable

