Traceback (most recent call last):
  File "C:\Users\Jesse Bond\AppData\Local\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Jesse Bond\AppData\Local\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Jesse Bond\AppData\Local\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Jesse Bond\AppData\Local\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Jesse Bond\AppData\Local\anaconda3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Jesse Bond\AppData\Local\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Jesse Bond\AppData\Local\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Jesse Bond\AppData\Local\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def volcalc(N):
    FAf = 1 #mol/min
    CAf = 1 #mol/L
    k   = 1 #1/min
    XA  = 0.9
    DX  = XA/N
    
    reactorset = np.linspace(1, N, N)
    V   = np.zeros(N)
    
    for index, n in enumerate(reactorset):
         V[index] = FAf/CAf/k*DX/(1 - n*DX)
    Vtot = sum(V)
    return [Vtot, V]
volcalc(1.0)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[14], line 15[0m
[0;32m     13[0m     Vtot [38;5;241m=[39m [38;5;28msum[39m(V)
[0;32m     14[0m     [38;5;28;01mreturn[39;00m [Vtot, V]
[1;32m---> 15[0m [43mvolcalc[49m[43m([49m[38;5;241;43m1.0[39;49m[43m)[49m

Cell [1;32mIn[14], line 8[0m, in [0;36mvolcalc[1;34m(N)[0m
[0;32m      5[0m XA  [38;5;241m=[39m [38;5;241m0.9[39m
[0;32m      6[0m DX  [38;5;241m=[39m XA[38;5;241m/[39mN
[1;32m----> 8[0m reactorset [38;5;241m=[39m [43mnp[49m[38;5;241;43m.[39;49m[43mlinspace[49m[43m([49m[38;5;241;43m1[39;49m[43m,[49m[43m [49m[43mN[49m[43m,[49m[43m [49m[43mN[49m[43m)[49m
[0;32m      9[0m V   [38;5;241m=[39m np[38;5;241m.[39mzeros(N)
[0;32m     11[0m [38;5;28;01mfor[39;00m index, n [38;5;129;01min[39;00m [38;5;28menumerate[39m(reactorset):

File [1;32m~\AppData\Local\anaconda3\lib\site-packages\numpy\core\function_base.py:122[0m, in [0;36mlinspace[1;34m(start, stop, num, endpoint, retstep, dtype, axis)[0m
[0;32m     24[0m [38;5;129m@array_function_dispatch[39m(_linspace_dispatcher)
[0;32m     25[0m [38;5;28;01mdef[39;00m [38;5;21mlinspace[39m(start, stop, num[38;5;241m=[39m[38;5;241m50[39m, endpoint[38;5;241m=[39m[38;5;28;01mTrue[39;00m, retstep[38;5;241m=[39m[38;5;28;01mFalse[39;00m, dtype[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[0;32m     26[0m              axis[38;5;241m=[39m[38;5;241m0[39m):
[0;32m     27[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[0;32m     28[0m [38;5;124;03m    Return evenly spaced numbers over a specified interval.[39;00m
[0;32m     29[0m 
[1;32m   (...)[0m
[0;32m    120[0m 
[0;32m    121[0m [38;5;124;03m    """[39;00m
[1;32m--> 122[0m     num [38;5;241m=[39m [43moperator[49m[38;5;241;43m.[39;49m[43mindex[49m[43m([49m[43mnum[49m[43m)[49m
[0;32m    123[0m     [38;5;28;01mif[39;00m num [38;5;241m<[39m [38;5;241m0[39m:
[0;32m    124[0m         [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124m"[39m[38;5;124mNumber of samples, [39m[38;5;132;01m%s[39;00m[38;5;124m, must be non-negative.[39m[38;5;124m"[39m [38;5;241m%[39m num)

[1;31mTypeError[0m: 'float' object cannot be interpreted as an integer
TypeError: 'float' object cannot be interpreted as an integer

