Traceback (most recent call last):
  File "C:\Users\Jesse Bond\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Jesse Bond\anaconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jesse Bond\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jesse Bond\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Jesse Bond\anaconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Jesse Bond\anaconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Jesse Bond\anaconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# plt.figure(figsize = (6,5))
# plt.contourf(Pset, Tset, Xout)
# plt.contourf(Pset, Tset, Xout, levels = np.linspace(0, 1.0, 201))
# plt.contourf(Pset, Tset, Xout, levels = np.linspace(0, 1.0, 201), cmap = 'jet')
# plt.xlim(Pset[0], Pset[-1])
# plt.xlabel('Pressure (bar)', fontsize = 14)
# plt.ylim(Tset[0], Tset[-1])
# plt.ylabel('Temperature (K)', fontsize = 14)
# plt.colorbar(ticks = np.arange(0, 1.1, 0.2))
plt.show()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[22], line 10[0m
[0;32m      1[0m [38;5;66;03m# plt.figure(figsize = (6,5))[39;00m
[0;32m      2[0m [38;5;66;03m# plt.contourf(Pset, Tset, Xout)[39;00m
[0;32m      3[0m [38;5;66;03m# plt.contourf(Pset, Tset, Xout, levels = np.linspace(0, 1.0, 201))[39;00m
[1;32m   (...)[0m
[0;32m      8[0m [38;5;66;03m# plt.ylabel('Temperature (K)', fontsize = 14)[39;00m
[0;32m      9[0m [38;5;66;03m# plt.colorbar(ticks = np.arange(0, 1.1, 0.2))[39;00m
[1;32m---> 10[0m plt[38;5;241m.[39mshow()

[1;31mNameError[0m: name 'plt' is not defined

